name: Release Dmenu

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y libxinerama-dev libxft-dev

    - name: Compile project
      run: make clean dmenu stest

    - name: Release Project
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./dmenu
          ./stest
